---
- name: clone omniture-to-pagerduty | git
  git:
    repo: "https://github.com/stevenharradine/omniture-to-pagerduty.git"
    dest: "{{ omniture_to_pagerduty_path }}"
    update: yes
    force: yes

- name: copy configuration
  template:
    src: templates/config.php
    dest: "{{ omniture_to_pagerduty_path }}/config.php"
    mode: 0644

- name: set cron jobs
  cron:
    name: "cron for github mfa checker"
    user: "{{ omniture_to_pagerduty_user }}"
    minute: "*"
    job: "php {{ omniture_to_pagerduty_path }}/connect.php"
